steps:
- name: 'gcr.io/cloud-builders/npm'  
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['test']

# 1263cc2b-9d97-473b-bf3e-22eed44ab1ce
- name: 'gcr.io/cloud-builders/npm'
  args: ['codecov', '-t', '$_CODECOV_TOKEN']

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/test-github-nuxt', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/test-github-nuxt']

timeout: '1600s'