steps:
- name: 'gcr.io/cloud-builders/npm'  
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ["test", "--", "--coverage"]

# - name: node:10.15.1
#   entrypoint: npm
#   args: ["run", "build"]

# Send Codecov
- name: 'gcr.io/cloud-builders/npm'  
  args: 
   [
     'run',
     'codecov',
     '--',
     '--token=$_CODECOV_TOKEN',
     '--disable=detect',
     '--commit=$COMMIT_SHA',
     '--branch=$BRANCH_NAME',
     '--build=$BUILD_ID',
   ]

# Try Build the container image before PR merge
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/test-github-nuxt', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/test-github-nuxt']

timeout: '1600s'