steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/test-github-nuxt', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/test-github-nuxt']

# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'test-github-nuxt'
  - '--platform'
  - 'managed'
  - '--region'
  - 'asia-east1'
  - '--project'
  - '$PROJECT_ID'
  - '--image'
  - 'gcr.io/$PROJECT_ID/test-github-nuxt'
images:
- 'gcr.io/$PROJECT_ID/test-github-nuxt'

timeout: '1600s'
